version: '2.1'

services:
    sensor-data:
        container_name: sensor-data
        build:
            context: .
            dockerfile: Dockerfile
        image: sensor-data:latest
        environment:
            NODE_ENV: development
            PROXY_PORT: 8085
            HTTP_PORT: 8082
        ports: #Forwarded from host to docker container
            - 8082:8082 # main application
            - 8085:8085 # proxy service
        volumes:
            - ./src:/code/src
            - ./static:/code/static
            - ./node_modules:/code/node_modules
            - ./package.json:/code/package.json
            #Execute npm link in hslayers-ng repo and then npm link hslayers-ng in this repo
            - ${HSLPATH}:/code/node_modules/hslayers-ng 
